### PR TITLE
Add support for pre- and post-snapshot scripts (#39)

### PR DESCRIPTION
**Pull request by tuffnatty**
As per issue #39.

### CODE REVIEW

**Comment by psy0rz** [comment]
thanks for taking the time to add this feature!

There is a small problem: What happens if the snapshot command throws an error? The post script wont be runned and the database wont be unfreezed for example.

So you, that part needs a try: finally: block.

**Comment by tuffnatty** [comment]
True that!

**Comment by tuffnatty** [comment]
The case was somewhat handled using the timeout in the --pre-snapshot-cmd example. However, try..finnally resolves it faster.

**Comment by psy0rz** [comment]
ok looks good..ill merge it and review it and make some minor tweaks perhaps, thanks!

**Comment by psy0rz** [comment]
> The case was somewhat handled using the timeout in the --pre-snapshot-cmd example. However, try..finnally resolves it faster.

and more reliable. (e.g. now you dont have to think about it, since the post is always executed)

**Pull request merged**
