### PR TITLE
Implement Issue #245 Snapshot exclude patterns

### PR DESCRIPTION
**Pull request by exi**
Issue #245

This is mostly a first draft without tests, but it seems to work and i'm using these changes on top of v3.2.2 on my server.

The primary point why I needed this is because in the time zfs_autobackup runs, my zfs-autosnapshot has taken and removed multiple "frequent" snapshots, which leads to autobackup failures.
I just want autobackup the snapshots with "monthly", "weekly" and "daily" in the name.

### CODE REVIEW

**Comment by exi** [comment]
@psy0rz I just wanted to get early feedback if this approach seems reasonable. I know you don't have much time to implement it yourself, so worst case i'll just use my own patched version on my server for the time being.

**Comment by psy0rz** [comment]
looks good, but "is_exluded" is too generic a name i think?

**Comment by psy0rz** [comment]
uh oohh some tests failed?

**Comment by psy0rz** [comment]
oh nevermind they were already broken, i'll have to fix that first

**Comment by psy0rz** [comment]
i fixed all the tests, can you rebase on master so that we can run the tests?

**Comment by exi** [comment]
@psy0rz rebased ✅

**Comment by psy0rz** [comment]
thanks!

**Pull request merged**
