### PR TITLE
Implement chunk size argument and refactor mbuffer command generation

### LINKED ISSUE #203: Feature request - Allow one to change mbuffer chunk size.
Hey,

The default chunk size of 128k for mbuffer is not always ideal. Would it be possible to either make it changeable or to accept a PR with the code modifications?

Cheers!
PEB

### PR DESCRIPTION
**Pull request by P-EB**
Would fix #203

### CODE REVIEW

**Comment by psy0rz** [comment]
looks fine, but could you rename it to --buffer-chunk-size? (or something that starts with --buffer-)

**Comment by P-EB** [comment]
Sure! Be my guest!

**Comment by P-EB** [comment]
(done)

**Comment by psy0rz** [comment]
thanks!

**Pull request merged**
